/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package AlmacenPresentacion;

import AlmacenClases.Boticas;
import AlmacenClases.Grupos;
import AlmacenDatos.DBBoticas;
import AlmacenDatos.DBGrupos;
import ComponentePresentacion.FrmPanelFondoPrincipal;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author jsarango
 */
public class FrmPedirBoticaGrupo extends javax.swing.JFrame {

    /**
     * Creates new form FrmPedirBoticaGrupo
     */
    public static String HoraIncioEnviar;
    List<Grupos> ListaGrupos;
    List<Boticas> ListaBoticas;


    public FrmPedirBoticaGrupo() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        FrmPanelFondoPrincipal fondoprinc = new FrmPanelFondoPrincipal();
        this.setSize(500, 300);
        this.add(fondoprinc, BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
        this.pack();
        CargarGrupos();
        CargarBoticas();
        //System.out.println(ListaGrupos.size());
        for (Grupos grupos : ListaGrupos) {
            cboElegirGrupo.addItem(grupos.getDescripcion());
        }
        //System.out.println(ListaGrupos.size());
        for (Boticas boticas : ListaBoticas) {
            cboElegirBotica.addItem(boticas.getDescripcion());
        }
        Date HoraActual = new Date();
        txtHoraInicio.setText(Integer.toString(HoraActual.getHours()) + ":" + Integer.toString(HoraActual.getMinutes()) + ":" + Integer.toString(HoraActual.getSeconds()));
        txtHoraInicio.setEnabled(false);
        HoraIncioEnviar=txtHoraInicio.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboElegirGrupo = new javax.swing.JComboBox();
        cboElegirBotica = new javax.swing.JComboBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Botica y grupo");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Elegir Grupo:");

        jLabel2.setText("Elegir Botica");

        jLabel3.setText("Hora Inicio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnAceptar)
                .addGap(34, 34, 34)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboElegirGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboElegirBotica, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboElegirGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cboElegirBotica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            
            Boticas botica = DBBoticas.buscarBoticaDescripcion(cboElegirBotica.getSelectedItem().toString(),null);
            Grupos grupo = DBGrupos.buscarGruposDescripcion(cboElegirGrupo.getSelectedItem().toString(),null);
            FrmRevisionGuias frmRev = new FrmRevisionGuias(botica,grupo);
            
            frmRev.txtHoraInicio.setText(HoraIncioEnviar);
            //frmRev.txtBotica_Descripcion.setText(cboElegirBotica.getSelectedItem().toString());
            //frmRev.txtGrupo_Descripcion.setText(cboElegirGrupo.getSelectedItem().toString());
            //try {
                //Boticas botica = DBBoticas.buscarBoticaDescripcion(cboElegirBotica.getSelectedItem().toString(),null);
                //frmRev.txtBotica.setText(botica.getCod_Descargo());
                //Grupos grupo = DBGrupos.buscarGruposDescripcion(cboElegirGrupo.getSelectedItem().toString(),null);
                //frmRev.txtGrupo.setText(String.valueOf(grupo.getId_Grupos()));
            //} catch (SQLException ex) {
            //    Logger.getLogger(FrmPedirBoticaGrupo.class.getName()).log(Level.SEVERE, null, ex);
            //}
            frmRev.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPedirBoticaGrupo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    private void CargarGrupos() {
        try {
            ListaGrupos = DBGrupos.mostrarGrupos();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPedirBoticaGrupo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void CargarBoticas() {
        try {
            ListaBoticas = DBBoticas.mostrarBoticas();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPedirBoticaGrupo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cboElegirBotica;
    private javax.swing.JComboBox cboElegirGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtHoraInicio;
    // End of variables declaration//GEN-END:variables
}
